### ISSUE TITLE
How to create a custom image - how-to

### ISSUE THREAD

**Issue by krzysztofantczak** [runabove/knowledge-base#57]
https://github.com/runabove/knowledge-base/blob/master/en/_posts/2014-05-16-how-to-create-a-custom-image-for-runabove.markdown

I think it's worth to mention which version of qemu was used in this tutorial. It took me a while to understand that my OS X qemu package (also freebsd package) was to old to apply described script/commands as it is. So if someone is using FBSD as a host, package qemu-devel should be installed (v2.2.0) and not 'qemu' (which is v0.11).

Also, it would be nice to see a note related to FreeBSD (and perhaps other *BSD based systems) that networking won't work out of the box without additional script - since gateway and network interface IP are in different subnets (/etc/rc.local):

```
GW=$(cat /var/db/dhclient.leases.vtnet0 | grep routers | cut -d" " -f5 | uniq | sed "s/;//")

route add -net "${GW}/32" -iface vtnet0
route add default "${GW}"
```

Also just to be sure that everything will work (in scenario when one wasn't using virtio based hardware when configuring machine), it's good to remove /var/db/dhclient* before deploying image to avoid getting wrong gateway address.

**Comment by NicolasLM** [comment]
Closing since RunAbove instances migrated to OVH.
