### ISSUE TITLE
Would you value a guide to format static web listing?

### ISSUE THREAD

**Issue by szepeviktor** [runabove/knowledge-base#78]
Example is here: http://mir.szepe.net/apaxy/

**Comment by szepeviktor** [comment]
@VincentCasse I would write the complete guide with a video like this:
https://www.youtube.com/watch?v=fCX43vTt-2c

**Comment by VincentCasse** [comment]
That's difficult to define the value of guide without the content :)

**Comment by szepeviktor** [comment]
@VincentCasse  The URL change, it has gone live:
http://mirror.szepe.net/

**Comment by NicolasLM** [comment]
Closing since RunAbove object storage migrated to OVH.
